apiVersion: v1
kind: Service
metadata:
  name: gitops-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: gitops-app
  ports:
    - name: http
      port: 80
      targetPort: http
