apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: gitops-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80

