apiVersion: v1
kind: Service
metadata:
  name: gitops-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gitops-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
