apiVersion: v1
kind: Service
metadata:
  name: gitops-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gitops-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80

